server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:eureka@localhost:8000/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instanceId: center-service
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
spring:
  application:
    name: center-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zzw.study:3306/ss-center
    username: root
    password: root123456